#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

# To see Ironic logs:
#   hypervisor/undercloud/podman-bash ironic_conductor
#   cat /var/log/ironic/ironic-conductor.log

# To change ironic.conf:
#   hypervisor/ssh undercloud-stack
#   vi /var/lib/config-data/puppet-generated/ironic/etc/ironic/ironic.conf
#   sudo podman restart ironic_conductor

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

UNDERCLOUD_CONF=$(cat "$ROOT/configuration/tripleo/undercloud.conf" | NAMESERVER="$NAMESERVER" envsubst)

"$ROOT/hypervisor/ssh" undercloud-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	m "[undercloud] Ensuring \"\$HOME/undercloud.conf\" exists"
	echo $(c "$UNDERCLOUD_CONF") > "\$HOME/undercloud.conf"

	m "[undercloud] Ensuring \"\$HOME/containers-prepare-parameter.yaml\" exists"
	openstack tripleo container image prepare default \
  		--local-push-destination \
  		--output-env-file "\$HOME/containers-prepare-parameter.yaml.original"

	# Annoyingly, TripleO by default locks some container images at specific versions while leaving
	# others at latest upstream versions, so we must make sure to lock those, too
	python <<- _EOT
		import yaml

		with open("\$HOME/containers-prepare-parameter.yaml.original") as f:
		     y = yaml.load(f)

		s = y["parameter_defaults"]["ContainerImagePrepare"][0]["set"]
		s["tag"] = $(q "$TRIPLEO_TAG")
		s["ceph_tag"] = $(q "$CEPH_TAG")

		with open("\$HOME/containers-prepare-parameter.yaml", "w") as f:
		    yaml.dump(y, f, default_flow_style=False)
	_EOT

	m '[undercloud] Ensuring undercloud is installed (~ 15 minutes)'
	openstack undercloud install

EOT
)"

m "Finished $(q "$(basename "$0")")!"
