#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html
# See: https://docs.openstack.org/tripleo-docs/latest/install/environments/baremetal.html#ironic-hardware-types

# All Ironic types and interfaces: https://opendev.org/openstack/ironic/src/branch/stable/stein/setup.cfg
# Note: Ironic fails to start with these: ibmc,fake-hardware
# Here is the full list:
# enabled_hardware_types = cisco-ucs-managed,cisco-ucs-standalone,fake-hardware,ibmc,idrac,ilo,ilo5,ipmi,irmc,manual-management,redfish,snmp,xclarity

# To see the logs:
#   hypervisor/undercloud/podman-bash ironic_conductor
#   cat /var/log/ironic/ironic-conductor.log

# To change ironic.conf
#   hypervisor/ssh undercloud-stack
#   /var/lib/config-data/puppet-generated/ironic/etc/ironic/ironic.conf
#   hypervisor/undercloud/podman-bash ironic_conductor

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$ROOT/hypervisor/ssh" undercloud-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$@\$RESET"; }

	m "[undercloud] Ensuring \"\$HOME/undercloud.conf\" exists"
	cat > "\$HOME/undercloud.conf" <<- _EOT
		[DEFAULT]
		undercloud_hostname = undercloud.localdomain
		undercloud_nameservers = $NAMESERVER
		local_interface = eth1
		enabled_hardware_types = cisco-ucs-managed,cisco-ucs-standalone,idrac,ilo,ilo5,ipmi,irmc,manual-management,redfish,snmp,xclarity
		enabled_boot_interfaces = fake,ilo-pxe,ilo-virtual-media,ipxe,irmc-pxe,irmc-virtual-media,pxe
		enabled_console_interfaces = fake,ilo,ipmitool-shellinabox,ipmitool-socat,no-console
		enabled_deploy_interfaces = ansible,direct,fake,iscsi,ramdisk
		enabled_inspect_interfaces = fake,idrac,ilo,inspector,irmc,no-inspect,redfish
		enabled_management_interfaces = cimc,fake,ibmc,idrac,ilo,impitool,irmc,noop,redfish,ucsm,xclarity
		enabled_network_interfaces = flat,neutron,noop
		enabled_power_interfaces = cimc,fake,ibmc,idrac,ilo,impitool,irmc,redfish,snmp,ucsm,xclarity
		enabled_raid_interfaces = agent,fake,idrac,ilo5,irmc,no-raid
		enabled_storage_interfaces = fake,noop,cinder,external
		enabled_vendor_interfaces = fake,ibmc,idrac,ilo,impitool,no-vendor
	_EOT

	m "[undercloud] Ensuring \"\$HOME/containers-prepare-parameter.yaml\" exists"
	openstack tripleo container image prepare default \
  		--local-push-destination \
  		--output-env-file "\$HOME/containers-prepare-parameter.yaml.original"

	python <<- _EOT
		import yaml

		with open("\$HOME/containers-prepare-parameter.yaml.original") as f:
		     y = yaml.load(f)

		s = y["parameter_defaults"]["ContainerImagePrepare"][0]["set"]
		s["tag"] = "$TRIPLEO_TAG"
		s["ceph_tag"] = "$CEPH_TAG"

		with open("\$HOME/containers-prepare-parameter.yaml", "w") as f:
		    yaml.dump(y, f, default_flow_style=False)
	_EOT

	m '[undercloud] Installing (~ 15 minutes)'
	openstack undercloud install

EOT
)"

m "Finished $(basename $0)!"
