#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

NAME=$1

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")

"$ROOT/hypervisor/ssh" -t undercloud-stack "$(cat <<- EOT

	if [ -z "$NAME" ]; then
		sudo podman ps --all --format '{{.Names}}'
	else
		CONTAINER_ID=\$(sudo podman ps --quiet --all --filter "name=$NAME")
		sudo podman exec -it "\$CONTAINER_ID" /bin/bash
	fi

EOT
)"
