#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$ROOT/hypervisor/create-virtual-machine" undercloud 80G centos7 "$CENTOS7_IMAGE"

"$ROOT/hypervisor/ssh" undercloud-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$@\$RESET"; }

	m '[hypervisor] Ensuring TripleO operating system packages are installed'
	sudo yum install --assumeyes \
		"$TRIPLEO_REPOS" \
		deltarpm wget
	sudo --preserve-env tripleo-repos \
		-b "$TRIPLEO_VERSION" \
		-d centos7 \
		current ceph
	# "python2-chardet" is workaround for: https://bugs.launchpad.net/tripleo/+bug/1829263
	sudo yum install --assumeyes \
		python2-tripleoclient python2-chardet \
		ceph-ansible

EOT
)"

m "Finished $(basename $0)!"
