#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$HERE/ssh" hypervisor-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	m '[hypervisor] Ensuring no libvirt virtual machines'
	for UUID in \$(virsh list --uuid); do
		virsh destroy "\$UUID"
	done
	for UUID in \$(virsh list --all --uuid); do
		virsh undefine "\$UUID" --managed-save --remove-all-storage --delete-snapshots --snapshots-metadata --nvram  
	done

	m '[hypervisor] Ensuring no libvirt volumes'
	for NAME in \$(virsh vol-list images 2> /dev/null | tail --lines=+3 | head --line=-1 | cut --fields=2 --delimiter=' '); do
		virsh vol-delete "\$NAME" --pool images
	done

	m '[hypervisor] Ensuring no libvirt networks'
	for UUID in \$(virsh -r net-list --all --uuid); do
		virsh net-undefine "\$UUID"
		virsh net-destroy "\$UUID"
	done

	m '[hypervisor] Ensuring no libvirt images'
	rm --recursive --force libvirt/
	rm --recursive --force .vbmc/

EOT
)"

"$HERE/ssh" hypervisor-root "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	m '[hypervisor] Ensuring no libvirt networks (root)'
	for UUID in \$(virsh -r net-list --all --uuid); do
		virsh net-undefine "\$UUID"
		virsh net-destroy "\$UUID"
	done

	m '[hypervisor] Ensuring no libvirt network bridges'
	ip link set os-ctlplane down || true
	brctl delbr os-ctlplane || true

 	systemctl stop vbmcd
 	systemctl disable vbmcd
	rm /etc/systemd/system/vbmcd.service
	systemctl daemon-reload

	#m '[hypervisor] Ensuring no user "stack"...'
	#if id -u stack > /dev/null; then
	#	userdel --force --remove stack
	#fi

EOT
)"

m "Finished $(q "$(basename "$0")")!"
