#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

C_HYPERVISOR_OPENSTACK_CONTROL_PLANE_INTERFACE=$(c "$HYPERVISOR_OPENSTACK_CONTROL_PLANE_INTERFACE")

"$HERE/ssh" hypervisor-root "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	m '[hypervisor-root] Ensuring no libvirt virtual machines'
	for UUID in \$(virsh list --uuid); do
		virsh destroy "\$UUID"
	done
	for UUID in \$(virsh list --all --uuid); do
		virsh undefine "\$UUID" --managed-save --remove-all-storage --delete-snapshots --snapshots-metadata --nvram  
	done

	m '[hypervisor-root] Ensuring no libvirt volumes'
	for NAME in \$(virsh vol-list images 2> /dev/null | tail --lines=+3 | head --line=-1 | cut --fields=2 --delimiter=' '); do
		virsh vol-delete "\$NAME" --pool images
	done

	m '[hypervisor-root] Ensuring no libvirt networks'
	for UUID in \$(virsh -r net-list --all --uuid); do
		virsh net-destroy "\$UUID"
	done
	for UUID in \$(virsh -r net-list --all --uuid); do
		virsh net-undefine "\$UUID"
	done

	m '[hypervisor-root] Ensuring no libvirt images'
	rm --recursive --force /home/stack/libvirt/

	m '[hypervisor-root] Ensuring no libvirt network bridges'
	nmcli connection delete os-ctlplane || true
	nmcli connection delete $C_HYPERVISOR_OPENSTACK_CONTROL_PLANE_INTERFACE || true

	m '[hypervisor-root] Ensuring VirtualBMC service is disabled'
 	systemctl stop vbmcd || true
 	systemctl disable vbmcd || true
	rm --force /etc/systemd/system/vbmcd.service
	systemctl daemon-reload
	rm --recursive --force /etc/virtualbmc/
	firewall-cmd --permanent --remove-port=6230/udp
	firewall-cmd --reload

	#m '[hypervisor-root] Ensuring no user "stack"...'
	#if id -u stack > /dev/null; then
	#	userdel --force --remove stack
	#fi

EOT
)"

m "Finished $(q "$(basename "$0")")!"
