#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://stafwag.github.io/blog/blog/2019/03/03/howto-use-centos-cloud-images-with-cloud-init/
# See: https://github.com/giovtorres/kvm-install-vm/blob/master/kvm-install-vm
# See: https://cloudinit.readthedocs.io/en/latest/index.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

NAME=$1
DISK_SIZE=$2
BASE=$3
BASE_IMAGE=$4

Q_NAME=$(q "$NAME")
EQ_NAME=$(eq "$NAME")
C_NAME=$(c "$NAME")
EQ_DISK_SIZE=$(eq "$DISK_SIZE")
C_DISK_SIZE=$(c "$DISK_SIZE")
EQ_BASE=$(eq "$BASE")
C_BASE_IMAGE=$(c "$BASE_IMAGE")

PASSWORD=$("$ROOT/utils/get-password" "stack@$NAME")

"$ROOT/utils/ensure-ssh-key-exists" "stack@$NAME"
KEY=$(< "$KEYS_ROOT/stack@$NAME.pub")

VIRT_INSTALL_ARGUMENTS=$(command_line_ini "$ROOT/configuration/libvirt/virt-install/$NAME.ini" |
	HOME=\$HOME \
	NAME=$EQ_NAME \
	envsubst)

CLOUD_CONFIG=$(cat "$ROOT/configuration/libvirt/cloud-init/$NAME.yaml" | 
	NAME=$EQ_NAME \
	NAMESERVER=$(eq "$NAMESERVER") \
	TIMEZONE=$(eq "$TIMEZONE") \
	PASSWORD=$(eq "$PASSWORD") \
	KEY=$(eq "$KEY") \
	envsubst)

m "[hypervisor] Ensuring keypair for virtual machine \"$NAME\" exists"
"$HERE/rsync" \
	"$KEYS_ROOT/stack@$NAME" \
	"$KEYS_ROOT/stack@$NAME.pub" \
	hypervisor-stack:keys/

"$HERE/ssh" -t hypervisor-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	chmod --recursive go-rwx "\$HOME/keys/"

	if ! virsh domstate $C_NAME 2> /dev/null; then
		if [ ! -f "\$HOME/libvirt/images/$EQ_NAME.qcow2" ]; then
			if [ ! -f "\$HOME/libvirt/images/$EQ_BASE.qcow2" ]; then
				m "[hypervisor] Downloading base image: \"\$HOME/libvirt/images/$EQ_BASE.qcow2\""
				mkdir --parents "\$HOME/libvirt/images/"
				wget --output-document="\$HOME/libvirt/images/$EQ_BASE.qcow2" $C_BASE_IMAGE
			fi

			m "[hypervisor] Creating virtual machine disk image: \"\$HOME/libvirt/images/$EQ_NAME.qcow2\" ($EQ_DISK_SIZE)"
			cp "\$HOME/libvirt/images/$EQ_BASE.qcow2" "\$HOME/libvirt/images/$EQ_NAME.qcow2"
			qemu-img resize "\$HOME/libvirt/images/$EQ_NAME.qcow2" $C_DISK_SIZE
		fi

		if [ ! -f "\$HOME/libvirt/images/$EQ_NAME-cloud-init.iso" ]; then
			m "[hypervisor] Creating cloud-init configuration disk image: "\$HOME/libvirt/images/$EQ_NAME-cloud-init.iso""
			CLOUD_INIT="\$HOME/libvirt/images/.${EQ_NAME}_cloud-init.yaml"

			echo $(c "$CLOUD_CONFIG") > "\$CLOUD_INIT"

			cloud-localds "\$HOME/libvirt/images/$EQ_NAME-cloud-init.iso" "\$CLOUD_INIT"
		fi

		m "[hypervisor] Creating virtual machine \"$EQ_NAME\""
		set -x
		virt-install \
			$VIRT_INSTALL_ARGUMENTS \
			--name $C_NAME \
			--disk "\$HOME/libvirt/images/$EQ_NAME-cloud-init.iso,device=cdrom"
	fi

	m "[hypervisor] Ensuring virtual machine \"$EQ_NAME\" will autostart"
	virsh autostart --domain $C_NAME

	m "[hypervisor] Ejecting cloud-init disk from \"$EQ_NAME\" virtual machine"
	virsh change-media $C_NAME hda --eject --config || true

EOT
)"

while true; do
	m "[hypervisor] Waiting for virtual machine \"$EQ_NAME\" to have an IP address..."

	ADDR=$("$HERE/ssh" hypervisor-stack "$(cat <<- EOT
		set -e
		virsh domifaddr $C_NAME --interface eth0 --source agent 2> /dev/null | \
			tail --lines=+3 | \
			head --lines=-1 | \
			awk '{ split(\$4,a,"/"); print \$3 "=" a[1] }'
	EOT
	)")

	if [ "$ADDR" != 'N/A=N' ]; then
		eval "$ADDR"
		if [ -n "$ipv4" ]; then
			break
		fi
	fi

	sleep 1
done

# Give it some time to fully come up
sleep 5

m "[$NAME] Ensuring keypair authorization for user \"stack\""
"$ROOT/utils/ensure-ssh-config" "$NAME-stack" "$ipv4" stack "stack@$NAME" hypervisor-stack
