#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://stafwag.github.io/blog/blog/2019/03/03/howto-use-centos-cloud-images-with-cloud-init/
# See: https://github.com/giovtorres/kvm-install-vm/blob/master/kvm-install-vm
# See: https://cloudinit.readthedocs.io/en/latest/index.html

IMAGE_NAME=$1
NAME=$2

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

EQ_IMAGE_NAME=$(eq "$IMAGE_NAME")
C_IMAGE_NAME=$(c "$IMAGE_NAME")

"$ROOT/utils/ensure-ssh-key-exists" "stack@$NAME"
KEY=$(< "$KEYS_ROOT/stack@$NAME.pub")

CLOUD_CONFIG=$(cat "$ROOT/configuration/libvirt/domains/$NAME/cloud-config.yaml" | 
	NAME=$EQ_NAME \
	NAMESERVER=$(eq "$NAMESERVER") \
	TIMEZONE=$(eq "$TIMEZONE") \
	PASSWORD=$(eq "$PASSWORD") \
	KEY=$(eq "$KEY") \
	envsubst)

"$ROOT/ssh" hypervisor-root "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	if [ -f $C_IMAGE_NAME ]; then
		m "[hypervisor-root] Cloud-init configuration disk image already exists: \"$EQ_IMAGE_NAME\""
		exit
	fi

	m "[hypervisor-root] Creating cloud-init configuration disk image: \"$EQ_IMAGE_NAME\""
	CONFIG="${EQ_IMAGE_NAME}.cloud-config.yaml"
	echo $(c "$CLOUD_CONFIG") > "\$CONFIG"
	cloud-localds $C_IMAGE_NAME "\$CONFIG"

EOT
)"
