#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://stafwag.github.io/blog/blog/2019/03/03/howto-use-centos-cloud-images-with-cloud-init/
# See: https://github.com/giovtorres/kvm-install-vm/blob/master/kvm-install-vm
# See: https://cloudinit.readthedocs.io/en/latest/index.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

NAME=$1
DISK_SIZE=$2
BASE=$3
BASE_IMAGE=$4

m "[hypervisor] Ensuring keypair for virtual machine \"$NAME\" exists"
"$ROOT/utils/ensure-ssh-key-exists" "stack@$NAME"
"$HERE/rsync" \
	"$KEYS_ROOT/stack@$NAME" \
	"$KEYS_ROOT/stack@$NAME.pub" \
	hypervisor-stack:keys/
"$HERE/ssh" hypervisor-stack "chmod --recursive go-rwx keys/"

VIRT_INSTALL=$(cat "$ROOT/configuration/libvirt/$NAME" | grep --invert-match '^#\|^$' | tr '\n' ' ')

"$HERE/ssh" -t hypervisor-stack "$(cat <<- EOT

	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$@\$RESET"; }

	if [ ! -f "\$HOME/libvirt/images/$NAME.qcow2" ]; then
		if [ ! -f "\$HOME/libvirt/images/$BASE.qcow2" ]; then
			m "[hypervisor] Downloading base image: \"\$HOME/libvirt/images/$BASE.qcow2\""
			mkdir --parents "\$HOME/libvirt/images/"
			wget --output-document="\$HOME/libvirt/images/$BASE.qcow2" $(q "$BASE_IMAGE")
		fi

		m "[hypervisor] Creating virtual machine disk image: \"\$HOME/libvirt/images/$NAME.qcow2\" ($DISK_SIZE)"
		cp "\$HOME/libvirt/images/$BASE.qcow2" "\$HOME/libvirt/images/$NAME.qcow2"
		qemu-img resize "\$HOME/libvirt/images/$NAME.qcow2" "$DISK_SIZE"
		#qemu-img create -f qcow2 -o preallocation=metadata "libvirt/images/$NAME.qcow2" "$DISK_SIZE"
		#virt-resize --expand /dev/sda1 "libvirt/images/$BASE.qcow2" "libvirt/images/$NAME.qcow2"
	fi

	if [ ! -f "libvirt/images/$NAME-cloud-init.iso" ]; then
		m "[hypervisor] Creating cloud-init configuration disk image: \"\$HOME/libvirt/images/$NAME-cloud-init.iso\""
		PASSWORD="$("$ROOT/utils/get-password" "stack@$NAME")"
		KEY=\$(< "\$HOME/keys/stack@$NAME.pub")
		CLOUD_INIT=\$(mktemp --tmpdir="\$HOME/libvirt/images" ".${NAME}_cloud-init.yaml.XXXXXXXX")

		# Note: we are purposely not doing runcmd "dhclient eth1" below because TripleO will be
		# taking over that interface

		cat > "\$CLOUD_INIT" <<- _EOT
			#cloud-config

			output: 
			  all: ">> /var/log/cloud-init.log"

			preserve_hostname: false
			hostname: "$NAME"
			fqdn: "$NAME.localdomain"

			network:
			  version: 1
			  config:
			  - type: nameserver
			    address: $NAMESERVER
			  - type: physical
			    name: eth0
			    subnets:
			    - type: dhcp
			  - type: physical
			    name: eth1
			    subnets:
			    - type: dhcp

			users:
			- name: stack
			  groups: wheel
			  shell: /bin/bash
			  sudo: ALL=(ALL) NOPASSWD:ALL
			  lock_passwd: false
			  passwd: "\$PASSWORD"
			  ssh-authorized-keys:
			  - \$KEY

			runcmd:
			- systemctl disable cloud-init.service
		_EOT

		cloud-localds "\$HOME/libvirt/images/$NAME-cloud-init.iso" "\$CLOUD_INIT"

		#rm "\$CLOUD_INIT"
	fi

	# Run "osinfo-query os" to see options
	m "[hypervisor] Ensuring virtual machine \"$NAME\" exists"
	virt-install \
		--name "$NAME" \
		--virt-type kvm \
		--graphics none \
		--noautoconsole \
		--network bridge=br-external,model=virtio \
		--network bridge=br-controlplane,model=virtio \
		--os-type linux \
		--os-variant centos7.0 \
		--import --disk path="\$HOME/libvirt/images/$NAME.qcow2,device=disk,bus=virtio" \
		--disk "\$HOME/libvirt/images/$NAME-cloud-init.iso,device=cdrom" \
		$VIRT_INSTALL

	m "[hypervisor] Ensuring virtual machine \"$NAME\" will autostart"
	virsh autostart --domain "$NAME"

	m "[hypervisor] Ejecting cloud-init disk from \"$NAME\" virtual machine"
	virsh change-media "$NAME" hda --eject --config || true

EOT
)"

while true; do
	m "[hypervisor] Waiting for virtual machine \"$NAME\" to have an IP address..."

	ADDR=$("$HERE/ssh" hypervisor-stack "$(cat <<- EOT
		virsh domifaddr "$NAME" --interface eth0 --source agent | \
			tail --lines=+3 | \
			head --lines=-1 | \
			awk '{ split(\$4,a,"/"); print \$3 "=" a[1] }'
	EOT
	)")

	if [ "$ADDR" != 'N/A=N' ]; then
		eval "$ADDR"
		if [ -n "$ipv4" ]; then
			break
		fi
	fi

	sleep 1
done

# Give it a second to fully come up
sleep 1

m "[$NAME] Ensuring keypair authorization for user \"stack\""
"$ROOT/utils/ensure-ssh-config" "$NAME-stack" "$ipv4" stack "stack@$NAME" hypervisor-stack
