#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

NAME=$1
PORT=$2

EQ_NAME=$(eq "$NAME")
C_NAME=$(c "$NAME")
C_PORT=$(c "$PORT")
C_VIRTUALBMC_USERNAME=$(c "$VIRTUALBMC_USERNAME")
C_VIRTUALBMC_PASSWORD=$(c "$VIRTUALBMC_PASSWORD")

"$ROOT/ssh" hypervisor-root "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m "[hypervisor-root] Ensuring VirtualBMC configured for virtual machine \"$EQ_NAME\""

	vbmc delete $C_NAME || true

	vbmc add $C_NAME \
		--address 192.168.122.1 \
		--port $C_PORT \
		--username $C_VIRTUALBMC_USERNAME \
		--password $C_VIRTUALBMC_PASSWORD

	vbmc start $C_NAME

	firewall-cmd --permanent --add-port=$C_PORT/udp
	firewall-cmd --reload

EOT
)"