#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

#rsync "$ROOT/configuration/undercloud.conf" "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS:tripleo/"
#ssh "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS" "mkdir --parents libvirt/configuration/"
#rsync --recursive "$ROOT/configuration/libvirt/user-data.base" "$ROOT/configuration/libvirt/meta-data" "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS:libvirt/configuration/"

"$HERE/create-virtual-machine" undercloud 80G centos7 "$CENTOS7_IMAGE"

m "Finished $(basename $0)!"
