#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

"$HERE/prepare"
"$HERE/undercloud/prepare"
"$HERE/undercloud/install"
"$HERE/overcloud/install"
