#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

"$HERE/provision-virtual-resources"
"$HERE/install-undercloud"
"$HERE/prepare-overcloud"
"$HERE/install-overcloud"
"$HERE/validate-overcloud"
