#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

#rsync "$ROOT/configuration/undercloud.conf" "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS:tripleo/"
#ssh "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS" "mkdir --parents libvirt/configuration/"
#rsync --recursive "$ROOT/configuration/libvirt/user-data.base" "$ROOT/configuration/libvirt/meta-data" "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS:libvirt/configuration/"

LINE="$(cat "$ROOT/configuration/libvirt/virt-install" | grep --invert-match '^#\|^$' | tr '\n' ' ')"

# See: https://github.com/giovtorres/kvm-install-vm/blob/master/kvm-install-vm

m "[hypervisor] Ensuring virtual machine base image exists"
ssh -t "$HYPERVISOR_USER@$HYPERVISOR_ADDRESS" \
"if [ ! -f libvirt/images/centos7.qcow2 ]; then
	mkdir --parents libvirt/images/
	wget --output-document=libvirt/images/centos7.qcow2 $(q "$CENTOS7_IMAGE")
fi

if [ ! -f ~/.ssh/id_rsa ]; then
	ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
fi"

"$HERE/create-virtual-machine" centos7 undercloud 80G

m "Finished $(basename $0)!"
