#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

# See: https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/ceph_config.html

# WORKAROUND: "ERROR! the playbook: /usr/share/ceph-ansible/site-docker.yml.sample could not be found"
"$HERE/ssh" undercloud "sudo yum --assumeyes install ceph-ansible"

"$HERE/tripleo-quickstart" \
	--playbook quickstart-extras-overcloud.yml \
	--tags all \
	--retain-inventory \
	--teardown none

echo "Finished $(basename $0)!"
