#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PORT=${1:-6230}

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$HERE/ssh" hypervisor-stack \
"ipmitool -I lanplus -U admin -P password -H 127.0.0.1 -p $(c "$PORT") $(c "${@:2}")"
