#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"

if [ -f "$TRIPLEO_QUICKSTART_WORKSPACE/ssh.config.ansible" ]; then

	scp \
		-F "$TRIPLEO_QUICKSTART_WORKSPACE/ssh.config.ansible" \
		-o LogLevel=ERROR \
		"$@"

else
	
	exit 1

fi