#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

"$HERE/tripleo-quickstart" \
	--playbook quickstart-extras-validate.yml \
	--tags all \
	--retain-inventory \
	--teardown none

echo "Finished $(basename $0)!"
