#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/utils/functions"

#virsh --connect="qemu+ssh://$HYPERVISOR_USER@$HYPERVISOR_ADDRESS/system" $LINE

if [ "$1" == '-r' ]; then

	"$HERE/ssh" hypervisor-root \
	"virsh $(c "${@:2}")"

else

	"$HERE/ssh" hypervisor-stack \
	"virsh $(c "$@")"

fi
