#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$HERE
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

"$ROOT/manager/all" "$1"
"$ROOT/openstack/all"
