#!/bin/bash
set -e

# See: https://infrared.readthedocs.io/en/stable/cloud-config.html

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/infrared-activate"

mkdir --parents "$HERE/work"

infrared workspace checkout onap-lab

rm --force "$HERE/work/configure-overcloud.log"
ANSIBLE_LOG_PATH="$HERE/work/configure-overcloud.log" \
infrared cloud-config -vv \
	--output "$HERE/work/configure-overcloud.yaml" \
	--from-file "$HERE/conf/configure-overcloud.ini"

echo Done!
