#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1
NAME=$2

if [ -z "$PROJECT" ] || [ -z "$NAME" ]; then
        echo 'Provide project name and server name'
        exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

# Create keypair (not associated with a project)
set +e
"$HERE/create-keypair" "$PROJECT"
set -e

# Create project
echo "Creating project \"$PROJECT\"..."
"$HERE/openstack" project create "$PROJECT" \
	--parent common \
	--description "$PROJECT" > /dev/null

echo "Adding admin role for user \"admin\" on project \"$PROJECT\"..."
# This will allow us to login with user admin
"$HERE/openstack" role add admin \
	--project "$PROJECT" \
	--user admin

# Create network
"$HERE/create-network" "$PROJECT" private 192.0.2.0/24

echo "Creating security group rules for ICMP and ssh for ports of project \"$PROJECT\"..."
# Projects are created with a security group named "default", we'll just update it
SECURITY_GROUP_ID=$("$HERE/openstack" security group list --project "$PROJECT" --column ID --format value | tail -n1)
"$HERE/openstack" security group rule create "$SECURITY_GROUP_ID" --remote-ip 0.0.0.0/0 --protocol tcp --dst-port 22:22 > /dev/null
"$HERE/openstack" security group rule create "$SECURITY_GROUP_ID" --remote-ip 0.0.0.0/0 --protocol icmp --icmp-type -1 --icmp-code -1 > /dev/null

# Create server
# Note: "server create" does not support a "--project" switch, so we'll have to use "openstack-project"
echo "Creating server \"$NAME\"..."
# Note: "--wait" causes an empty line to be printed before id
SERVER_ID=$("$HERE/openstack-project" "$PROJECT" server create "$NAME" \
	--column id \
	--format value \
	--wait \
	--flavor m1.large \
	--image common.centos7 \
	--network "$PROJECT.private" \
	--key-name "$PROJECT" | tail -n1)

# Create volume
"$HERE/create-volume" "$PROJECT" "$NAME" 2

# Create floating IP
echo "Creating floating IP on \"public\"..."
FLOATING_IP_ID=$("$HERE/openstack" floating ip create public \
	--project "$PROJECT" \
	--column id \
	--format value)

FLOATING_IP=$("$HERE/openstack" floating ip show "$FLOATING_IP_ID" \
	--column floating_ip_address \
	--format value)

# Add floating IP to server
echo "Adding floating IP to server \"$NAME\"..."
"$HERE/openstack-project" "$PROJECT" server add floating ip "$SERVER_ID" "$FLOATING_IP_ID"

echo 'Done! To login:'
echo "\"$HERE/ssh-virtual\" -i \"$OPENSTACK_KEYPAIRS/$PROJECT\" centos@$FLOATING_IP"
