#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://www.server-world.info/en/note?os=CentOS_7&p=openstack_queens&f=6

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

mkdir --parents "$CLOUD_IMAGES"

function create ()
{
	local IMAGENAME=$1
	local URL=$2
	local FILENAME="$OPENSTACK_IMAGES/$(basename "$URL")"

	if [ ! -f "$FILENAME" ]; then
		wget --output-document="$FILENAME" "$URL"
	fi

	"$HERE/openstack" image create "$IMAGENAME" \
		--file "$FILENAME" \
		--disk-format qcow2 \
		--container-format bare \
		--public
}

create 'CentOS 7' "$CENTOS7_IMAGE"
