#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=test

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

# Create keypair (not associated with a project)
set +e
"$HERE/create-keypair" "$PROJECT"
set -e

# Create project
echo "Creating project \"$PROJECT\"..."
"$HERE/openstack" project create "$PROJECT" \
	--parent common \
	--description "$PROJECT" > /dev/null

echo "Adding admin role..."
"$HERE/openstack" role add admin \
	--project "$PROJECT"
	--user admin

# Create network
"$HERE/create-network" "$PROJECT" private 192.0.2.0/24

echo "Creating security group rules..."
SECURITY_GROUP_ID=$("$HERE/openstack" security group list --project "$PROJECT" --column ID --format value | tail -n1)
"$HERE/openstack" security group rule create "$SECURITY_GROUP_ID" --remote-ip 0.0.0.0/0 --protocol tcp --dst-port 22:22 > /dev/null
"$HERE/openstack" security group rule create "$SECURITY_GROUP_ID" --remote-ip 0.0.0.0/0 --protocol icmp --icmp-type -1 --icmp-code -1 > /dev/null

# Create server
# Note: We cannot create a server on a different project than the current one, so we'll use our "openstack-project"
echo "Creating server..."
SERVER_ID=$("$HERE/openstack-project" "$PROJECT" server create hello-world \
	--column id \
	--format value \
	--flavor m1.tiny \
	--image common.centos7 \
	--network test.private \
	--key-name "$PROJECT")

# Create floating IP
echo "Creating floating IP..."
FLOATING_IP_ID=$("$HERE/openstack" floating ip create nova \
	--project "$PROJECT" \
	--column id \
	--format value)
FLOATING_IP=$("$HERE/openstack" floating ip show "$FLOATING_IP_ID" \
	--column floating_ip_address
	--format value)

# Add floating IP to server
echo "Adding floating IP to server..."
"$HERE/openstack" server add floating ip "$SERVER_ID" "$FLOATING_IP_ID"

echo 'Done! To login:'
echo "ssh -i \"$OPENSTACK_KEYPAIRS/$PROJECT\" centos@$FLOATING_IP"
