#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

"$HERE/tripleo-quickstart" \
	--tags all \
	--nodes "$QUICKSTART_WORK/config/nodes/1ctlr_1comp.yml" \
	--playbook quickstart-extras-undercloud.yml \
	--retain-inventory \
	--teardown none \
	"$HYPERVISOR_ADDRESS"

echo Done!

# GUI
# See: https://docs.openstack.org/tripleo-docs/latest/install/basic_deployment/basic_deployment_ui.html#access-the-ui
# https://onap1
# user = admin
# password = ./ssh-hypervisor undercloud "sudo hiera keystone::admin_password"
