#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
cd "$HERE"

sudo ./reset-virtual-resources
./clean-infrared
./install-infrared
./delete-virtual-resources
./provision-virtual-resources
./install-undercloud
./build-cloud-images
./install-overcloud
