#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

mkdir --parents "$ORCHESTRATOR_ROOT"

curl \
	--output "$ORCHESTRATOR_ROOT/quickstart.sh" \
	"https://raw.githubusercontent.com/openstack/tripleo-quickstart/$QUICKSTART_COMMIT/quickstart.sh"
chmod +x "$ORCHESTRATOR_ROOT/quickstart.sh"

# See: https://bugs.launchpad.net/tripleo/+bug/1820945
curl \
	--output "$ORCHESTRATOR_ROOT/bindep.txt" \
	"https://raw.githubusercontent.com/openstack/tripleo-quickstart/$QUICKSTART_COMMIT/bindep.txt"

#"$HERE/tripleo-quickstart" --install-deps

echo Done!
