#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# Requirements
# sudo yum install git libselinux-python
# sudo pip install virtualenv==16.0.0

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/env"

if [ ! -d "$INFRARED_SOURCE" ]; then
	git clone --single-branch -b "$INFRARED_BRANCH" https://github.com/redhat-openstack/infrared.git "$INFRARED_SOURCE"
	pushd "$INFRARED_SOURCE"
	git reset --hard "$INFRARED_COMMIT"
	popd
fi

if [ ! -d "$INFRARED_VIRTUALENV" ]; then
	virtualenv "$INFRARED_VIRTUALENV"
	# Allow running on localhost (Orchestrator and Hypervisor are same machine)
	ln --symbolic /usr/lib64/python2.7/site-packages/selinux "$INFRARED_VIRTUALENV/lib64/python2.7/site-packages/selinux"
fi

mkdir --parents "$IR_HOME"

. "$HERE/infrared-activate"

pip install --upgrade pip==18.1
pip install --upgrade setuptools==40.4.3
pip install "$INFRARED_SOURCE"

# Using tox to install:
#pip install --upgrade tox==3.5.2
#tox --workdir "$INFRARED_SOURCE" -e cli

INFRARED_INSTALLED="$INFRARED_VIRTUALENV/lib/python2.7/site-packages/infrared"

# Patch for: https://github.com/redhat-openstack/infrared/issues/337
sed --in-place '0,/name: virtualbmc$/{s/name: virtualbmc$/name: virtualbmc==1.4.0/}' "$INFRARED_INSTALLED/common/roles/vbmc/tasks/install.yml"
#sed --in-place 's/name: python-virtualbmc/name: python2-virtualbmc/' "$INFRARED_INSTALLED/common/roles/vbmc/tasks/install.yml"

# Patch for: Nova doing wrong health check (tripleo)
# TODO

# Patch for ceph-mgr deployment broken (tripleo)
# TODO

set +e

infrared plugin add "$INFRARED_SOURCE/plugins/virsh"
infrared plugin add "$INFRARED_SOURCE/plugins/tripleo-undercloud"
infrared plugin add "$INFRARED_SOURCE/plugins/tripleo-overcloud"

infrared workspace create onap-lab
