#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

sudo "$HERE/hypervisor/reset-virtual-resources"
"$HERE/clean-infrared"
"$HERE/install-infrared"
"$HERE/delete-virtual-resources"
"$HERE/provision-virtual-resources"
"$HERE/install-undercloud"
"$HERE/build-undercloud-images"
"$HERE/install-overcloud"
