#!/bin/bash
set -e

# See: https://infrared.readthedocs.io/en/stable/tripleo-undercloud.html
# See: https://hub.docker.com/u/tripleorocky with prefix "centos-binary-"

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/infrared-activate"

mkdir --parents "$HERE/work"

infrared workspace checkout onap-lab

rm --force "$HERE/work/install-undercloud.log"
ANSIBLE_LOG_PATH="$HERE/work/install-undercloud.log" \
infrared tripleo-undercloud -vv \
	--output "$HERE/work/install-undercloud.yaml" \
	--from-file "$HERE/conf/undercloud.ini" \
    --version "$UNDERCLOUD_OPENSTACK_VERSION" \
	--registry-namespace "tripleo$OVERCLOUD_OPENSTACK_VERSION"

#    --build current-tripleo-rdo

# BUG: The "python-tripleoclient" package from "rocky" is broken for InfraRed
# See: https://bugs.launchpad.net/tripleo/+bug/1791970
# See: https://bugs.launchpad.net/tripleo/+bug/1817634
# Workaround: sudo mv /etc/pki/ca-trust/source/anchors/cm-local-ca.pem /etc/pki/ca-trust/source/anchors/cm-local-ca.pem.original && sudo cp /etc/pki/ca-trust/source/anchors/undercloud-cacert.pem /etc/pki/ca-trust/source/anchors/cm-local-ca.pem

"$HERE/ssh-hypervisor-virtual" undercloud-0 \ 
"mv /etc/pki/ca-trust/source/anchors/cm-local-ca.pem /etc/pki/ca-trust/source/anchors/cm-local-ca.pem.original && cp /etc/pki/ca-trust/source/anchors/undercloud-cacert.pem /etc/pki/ca-trust/source/anchors/cm-local-ca.pem"

#. /home/stack/stackrc && openstack tripleo container image prepare default --output-env-file containers-prepare-parameter.yaml
#cp tripleo-config-generated-env-files/undercloud_parameters.yaml containers-prepare-parameter.yaml

echo Done!
