#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/infrared-activate"

. "$IR_HOME/.workspaces/onap-lab/keystonerc"

OS_PROJECT_NAME=$1

openstack "${@:2}"
