#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

# Note: stackrc is backed up on Orchestrator at "$IR_HOME/.workspaces/onap-lab/stackrc"

"$HERE/ssh-hypervisor-virtual" stack@undercloud-0 \
". /home/stack/stackrc && openstack $@"
