#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/infrared-activate"

infrared workspace checkout onap-lab
infrared cloud-config -vv \
	--from-file "$HERE/conf/overcloud.ini"

"$HERE/openstack" project create common
"$HERE/create-common-flavors" common
"$HERE/create-common-images" common
