#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
	echo "Run this script as root"
	exit 1
fi

# libselinux-python: in order to allow ssh to localhost (required when Orchestrator and Hypervisor are same machine) 
# libvirt: to get the "virsh" command

dnf install \
git \
python-devel \
libselinux-python \
libvirt

# pip install virtualenv==16.4.3
