#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HOST=$1

if [ -z "$HOST" ]; then
	echo "Provide virtual host name"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

ssh -t -o LogLevel=QUIET "root@$HYPERVISOR_ADDRESS" \
ssh -t -o LogLevel=QUIET -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$HOST" \
\"${@:2}\"
