#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

CONTROLLER=${1:-virthost}

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

ssh \
	-F "$QUICKSTART_WORK/ssh.config.ansible" \
	-o LogLevel=ERROR \
	"$CONTROLLER" \
	"${@:2}"
