#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

MACHINE=$1

if [ -z "$MACHINE" ]; then
	echo "Provide machine name"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

eval $("$HERE/openstack-undercloud" server show --format value --column addresses "$MACHINE")

if [ -z "$ctlplane" ]; then
	echo "$MACHINE has no address on ctlplane network"
fi

sudo "$HERE/ssh-virtual" "heat-admin@$ctlplane"
