#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

"$HERE/tripleo-quickstart" \
	--tags all \
	--nodes "$QUICKSTART_WORK/config/nodes/1ctlr_1comp.yml" \
	--playbook quickstart-extras-validate.yml \
	--retain-inventory \
	--teardown none \
	"$HYPERVISOR_ADDRESS"

echo Done!
