#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/conf/env"

virsh --connect="qemu+ssh://root@$HYPERVISOR_ADDRESS/system" "$@" 
