#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-fetch-results"

UNDERCLOUD_CONF=$(cat "$ROOT/configuration/tripleo/undercloud.conf" |
	NAME=$(eq 'tripleo') \
	NAMESERVER=$(eq "$NAMESERVER") \
	envsubst)

"$ROOT/hypervisor/ssh" tripleo-stack "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m "[tripleo-stack] Updating \"\$HOME/undercloud.conf\""
	echo $(c "$UNDERCLOUD_CONF") > "\$HOME/undercloud.conf"

	# TODO: is there a way to use our own container-image-prepare.yaml?
	# See: /var/log/tripleo-container-image-prepare.log

	m '[tripleo-stack] Ensuring TripleO is installed (~ 15 minutes)'
	openstack undercloud install

EOT
)"
