#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-fetch-results"

UNDERCLOUD_CONF=$(cat "$ROOT/configuration/tripleo/undercloud.conf" |
	NAME=$(eq 'tripleo') \
	NAMESERVER=$(eq "$NAMESERVER") \
	envsubst)

"$ROOT/hypervisor/ssh" tripleo-stack "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m "[tripleo-stack] Updating \"\$HOME/undercloud.conf\""
	echo $(c "$UNDERCLOUD_CONF") > "\$HOME/undercloud.conf"

	m "[tripleo-stack] Updating \"\$HOME/containers-prepare-parameter.yaml\""

	# TODO: is this just for overcloud maybe???
	openstack tripleo container image prepare default \
  		--local-push-destination \
  		--output-env-file "\$HOME/containers-prepare-parameter.yaml.original"

	# Annoyingly, TripleO by default locks some container images at specific versions while leaving
	# others at latest upstream versions, so we must make sure to lock those, too
	python2 <<- _EOT
		import yaml

		with open("\$HOME/containers-prepare-parameter.yaml.original") as f:
		  y = yaml.load(f)

		s = y["parameter_defaults"]["ContainerImagePrepare"][0]["set"]
		s["tag"] = $(q "$TRIPLEO_TAG")
		s["ceph_tag"] = $(q "$CEPH_TAG")

		with open("\$HOME/containers-prepare-parameter.yaml", "w") as f:
		  yaml.dump(y, f, default_flow_style=False)
	_EOT

	m '[tripleo-stack] Ensuring TripleO is installed (~ 15 minutes)'
	openstack undercloud install

EOT
)"
