#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/utils/functions"

"$ROOT/hypervisor/ssh" -t tripleo-stack \
"sudo podman $(c "$@")"
