#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-fetch-results"

EQ_TRIPLEO_VERSION=$(eq "$TRIPLEO_VERSION")

"$ROOT/hypervisor/create-virtual-machine" tripleo 80G centos7 "$CENTOS7_IMAGE"

"$ROOT/hypervisor/ssh" -t tripleo-stack "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m '[tripleo-stack] Ensuring utility packages are installed'
	sudo yum install --assumeyes \
		deltarpm
	sudo yum upgrade --assumeyes
	sudo yum install --assumeyes \
		wget lynx

	if ! rpm --query --quiet python2-tripleo-repos; then
		m '[tripleo-stack] Ensuring TripleO repository is installed'

		# RDO deletes old packages from the repository when adding new versions, which means we
		# cannot rely on a stable URL. Instead we will scrape the repository's generated HTML index
		# using Lynx to find the current URL.
	
		TRIPLEO_REPOS=\$(lynx -listonly -nonumbers -dump  "https://trunk.rdoproject.org/centos7-$EQ_TRIPLEO_VERSION/consistent/" |
			grep '/python2-tripleo-repos-.*\.rpm$')

		# This 	
		sudo yum install --assumeyes \
			"\$TRIPLEO_REPOS"
		sudo yum upgrade --assumeyes
	fi

	m '[tripleo-stack] Ensuring TripleO-client packages are installed'
	sudo --preserve-env tripleo-repos \
		-b $(c "$TRIPLEO_VERSION") \
		-d centos7 \
		current ceph
	# "python2-chardet" is workaround for: https://bugs.launchpad.net/tripleo/+bug/1829263
	sudo yum upgrade --assumeyes
	sudo yum install --assumeyes \
		python2-tripleoclient python2-chardet \
		ceph-ansible

	m '[tripleo-stack] Updating OpenStack Cliff configuration'

	# For quality of life we will make sure that the "openstack" command (Cliff) will always limit
	# its output width to the width of our terminal ("CLIFF_FIT_WIDTH=1" doesn't seem to work)

	sed --in-place "/# OpenStack START/,/# OpenStack END/d" "\$HOME/.bashrc"
	cat >> "\$HOME/.bashrc" <<- _EOT
		# OpenStack START
		# For Cliff see: https://docs.openstack.org/cliff/stein/
		CLIFF_FIT_WIDTH=1
		function openstack_cliff () {
		  export CLIFF_MAX_TERM_WIDTH=\\\$(tput cols)
		}
		if [ "\\\$TERM" != dumb ]; then
		  openstack_cliff
		  trap openstack_cliff WINCH
		fi
		# OpenStack END
	_EOT

EOT
)"

m '[hypervisor-root] Rebooting virtual machine "tripleo"'
"$ROOT/hypervisor/virsh" reboot tripleo
