#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$ROOT/hypervisor/create-virtual-machine" tripleo 80G centos7 "$CENTOS7_IMAGE"

"$ROOT/hypervisor/ssh" tripleo-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	m '[hypervisor] Ensuring TripleO packages are installed'
	sudo yum install --assumeyes \
		$(c "$TRIPLEO_REPOS") \
		deltarpm wget
	sudo --preserve-env tripleo-repos \
		-b $(c "$TRIPLEO_VERSION") \
		-d centos7 \
		current ceph
	# "python2-chardet" is workaround for: https://bugs.launchpad.net/tripleo/+bug/1829263
	sudo yum install --assumeyes \
		python2-tripleoclient python2-chardet \
		ceph-ansible

	m '[hypervisor] Ensuring OpenStack cliff is configured'
	sed --in-place "/# OpenStack START/,/# OpenStack END/d" "\$HOME/.bashrc"
	cat >> "\$HOME/.bashrc" <<- _EOT
		# OpenStack START
		# For cliff see: https://docs.openstack.org/cliff/stein/
		function openstack_cliff () {
		  export CLIFF_MAX_TERM_WIDTH=\\\$(tput cols)
		}
		if [ "\\\$TERM" != dumb ]; then
		  openstack_cliff
		  trap openstack_cliff WINCH
		fi
		# OpenStack END
	_EOT

EOT
)"

m "Finished $(q "$(basename "$0")")!"
