#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1
NAME=$2
SIZE=$3

if [ -z "$PROJECT" ] || [ -z "$NAME" ] || [ -z "$SIZE" ]; then
	echo 'Provide project name, server name, and size in GB'
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")

if ! "$ROOT/openstack/openstack" volume list --project "$PROJECT" | grep --quiet --line-regexp --fixed-strings "$PROJECT.$NAME"; then

	echo "Creating volume \"$PROJECT.$NAME\"..."
	# NOTE: "volume create" has a "--project" switch, but it seems to be ignored
	VOLUME_ID=$("$ROOT/openstack-project" "$PROJECT" volume create "$PROJECT.$NAME" \
		--size "$SIZE" \
		--column id \
		--format value)

	echo "Adding volume \"$PROJECT.$NAME\" to server \"$NAME\"..."
	"$ROOT/openstack-project" "$PROJECT" server add volume "$NAME" "$PROJECT.$NAME"

else

        echo "Volume \"$PROJECT.$NAME\" already exists"
        exit 1

fi
