#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1

if [ -z "$PROJECT" ]; then
	echo 'Provide project name'
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")

function delete_resources () {
	local RESOURCE=$1
	local RESOURCE_ID

	echo "Deleting ${RESOURCE}s..."
	for RESOURCE_ID in $("$ROOT/openstack/openstack" "$RESOURCE" list --project "$PROJECT" --column ID --format value); do
		"$ROOT/openstack/openstack" "$RESOURCE" delete "$RESOURCE_ID"
	done
}

function delete_project_resources () {
	local RESOURCE=$1
	local RESOURCE_ID

	echo "Deleting ${RESOURCE}s..."
	for RESOURCE_ID in $("$ROOT/openstack-project" "$PROJECT" "$RESOURCE" list --column ID --format value); do
		"$ROOT/openstack-project" "$PROJECT" "$RESOURCE" delete "$RESOURCE_ID"
	done
}

delete_project_resources server
delete_project_resources volume

# We *must* remove ports from routers before deleting either the router or the ports
# NOTE: we cannot remove a port if it's associated with a server (command will not return error!)
echo 'Deleting routers...'
for ROUTER_ID in $("$ROOT/openstack/openstack" router list --project "$PROJECT" --column ID --format value); do
	for PORT_ID in $("$ROOT/openstack/openstack" port list --router "$ROUTER_ID" --column id --format value); do
		"$ROOT/openstack/openstack" router remove port "$ROUTER_ID" "$PORT_ID"
	done
	"$ROOT/openstack/openstack" router delete "$ROUTER_ID"
done

# Our networks might have ports from other projects
echo 'Deleting ports...'
for NETWORK_ID in $("$ROOT/openstack/openstack" network list --project "$PROJECT" --column ID --format value); do
	for PORT_ID in $("$ROOT/openstack/openstack" port list --network "$NETWORK_ID" --column id --format value); do
		"$ROOT/openstack/openstack" port delete "$PORT_ID"
	done
done

delete_resources subnet
delete_resources network 
delete_resources 'floating ip'
delete_resources 'security group' 

echo 'Deleting project...'
"$ROOT/openstack/openstack" project delete "$PROJECT"
