#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")

"$HERE/create-common-flavors"
"$ROOT/openstack/openstack" project create common
"$HERE/create-common-images" common
