#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

m '[openstack] Deleting common'
"$ROOT/openstack/openstack" \
stack delete common \
	--wait -v || true
