#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/ && rsync' \
	"$HERE/"*.yaml \
	manager:/home/manager/workloads/

m '[openstack] Creating common'
"$ROOT/openstack/openstack" \
stack create common \
	--template /home/manager/workloads/common.yaml \
	--parameter "centos7-image-url=$CENTOS7_IMAGE" \
	--wait -v
