#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/ && rsync' \
	"$HERE/"*.yaml \
	manager:/home/manager/workloads/

m '[openstack] Creating common'
"$ROOT/openstack/openstack" \
	stack create \
		--wait \
		--template /home/manager/workloads/common.yaml \
		--parameter "centos7-image-url=$CENTOS7_IMAGE" \
		common -v

m '[openstack] Creating hello-world-project'
"$ROOT/openstack/openstack" \
	stack create \
		--wait \
		--template /home/manager/workloads/hello-world-project.yaml \
		hello-world-project -v

m '[openstack] Creating hello-world'
"$ROOT/openstack/openstack-project" \
	hello-world hello-world-admin password \
	stack create \
		--wait \
		--template /home/manager/workloads/hello-world.yaml \
		hello-world -v

m '[openstack] Fetching hello-world private key'
"$ROOT/openstack/openstack-project" \
	hello-world hello-world-admin password \
	stack output show hello-world private-key --format value --column output_value \
	> "$KEYS_ROOT/centos@hello-world"
chmod 600 "$KEYS_ROOT/centos@hello-world"

"$ROOT/rsync" \
	"$KEYS_ROOT/centos@hello-world" \
	lab-controller-0:

IP_ADDRESS=$("$ROOT/openstack/openstack-project" \
	hello-world hello-world-admin password \
	stack output show hello-world public-ip --format value --column output_value)

m "[openstack] Server has public IP address: $IP_ADDRESS"

"$ROOT/utils/ensure-ssh-config" hello-world "$IP_ADDRESS" centos centos@hello-world lab-controller-0
