#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

UNDERCLOUD_CONF=$(cat "$ROOT/configuration/tripleo/undercloud.conf" |
	NAME=$(eq 'tripleo') \
	NAMESERVER=$(eq "$NAMESERVER") \
	envsubst)

"$ROOT/ssh" tripleo "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m "[tripleo] Updating \"\$HOME/undercloud.conf\""
	echo $(c "$UNDERCLOUD_CONF") > "\$HOME/undercloud.conf"

	# TODO: is there a way to use our own container-image-prepare.yaml?
	# See: /var/log/tripleo-container-image-prepare.log

	m '[tripleo] Ensuring TripleO is deployed (~ 15 minutes)'
	openstack \
	undercloud install \
		$(c "$TRIPLEO_VERBOSITY")

EOT
)"
