#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/utils/functions"

"$ROOT/ssh" tripleo \
"sudo ip netns exec \$(sudo ip netns list | cut --delimiter=' ' --fields=1) $(c "$@")"
