#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

# See: https://review.opendev.org/#/c/665324/
#      https://bugzilla.redhat.com/show_bug.cgi?id=1602844

STANDARD_PY=$(cat "$ROOT/patches/ironic-inspector/standard.py")

"$ROOT/ssh" tripleo "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	m '[tripleo] Patching "ironic_inspector"'
	MOUNT=\$(sudo podman mount ironic_inspector)
	echo $(c "$STANDARD_PY") | sudo tee "\$MOUNT/usr/lib/python2.7/site-packages/ironic_inspector/plugins/standard.py"

	m '[tripleo] Restarting "ironic_inspector"'
	sudo systemctl restart tripleo_ironic_inspector

EOT
)"
