#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

EQ_TRIPLEO_VERSION=$(eq "$TRIPLEO_VERSION")

"$ROOT/manager/create-virtual-machine" tripleo tripleo
"$ROOT/manager/enable-virtual-machine-control-plane" tripleo eth0 tripleo

"$ROOT/ssh" tripleo "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m '[tripleo] Ensuring utility packages are installed'

	sudo yum install --assumeyes \
		deltarpm

	sudo yum upgrade --assumeyes

	sudo yum install --assumeyes \
		bash-completion \
		wget lynx

	if ! rpm --query --quiet python2-tripleo-repos; then
		m '[tripleo] Ensuring TripleO repository is installed'

		# The RDO project deletes old packages from the repository when adding new versions, which
		# means we cannot in this script rely on a stable URL for the package. Our workaround is
		# to scrape the repository's generated HTML index using Lynx in order to find the current
		# URL.
	
		TRIPLEO_REPOS=\$(lynx -listonly -nonumbers -dump  "https://trunk.rdoproject.org/centos7-$EQ_TRIPLEO_VERSION/consistent/" |
			grep '/python2-tripleo-repos-.*\.rpm$')

		sudo yum install --assumeyes \
			"\$TRIPLEO_REPOS"

		sudo yum upgrade --assumeyes
	fi

	m '[tripleo] Ensuring TripleO-client packages are installed (~ 5 minutes)'

	sudo --preserve-env tripleo-repos \
		-b $(c "$TRIPLEO_VERSION") \
		-d centos7 \
		current ceph

	sudo yum upgrade --assumeyes

	sudo yum install --assumeyes \
		python2-tripleoclient \
		ceph-ansible

	m '[tripleo] Updating OpenStack Cliff configuration'

	# For quality of life we will make sure that the "openstack" command (Cliff) will always limit
	# its output width to the width of our terminal ("CLIFF_FIT_WIDTH=1" doesn't seem to work)

	sed --in-place "/# OpenStack START/,/# OpenStack END/d" "\$HOME/.bashrc"
	cat >> "\$HOME/.bashrc" <<- _EOT
		# OpenStack START
		# For Cliff see: https://docs.openstack.org/cliff/stein/
		function openstack_cliff () {
		  export CLIFF_MAX_TERM_WIDTH=\\\$(tput cols)
		}
		if [ "\\\$TERM" != dumb ]; then
		  trap openstack_cliff WINCH
		  openstack_cliff
		fi
		# OpenStack END
	_EOT

EOT
)"

m '[manager-root] Rebooting virtual machine "tripleo"'
"$ROOT/manager/virsh" reboot tripleo
