#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/ && rsync' \
	"$ROOT/configuration/openstack/heat/templates/hello-world-tenant.yaml" \
	"$ROOT/configuration/openstack/heat/templates/hello-world.yaml" \
	manager:/home/manager/workloads/

m '[openstack] Creating hello-world-tenant'
"$ROOT/openstack/openstack" \
stack create hello-world-tenant \
	--template /home/manager/workloads/hello-world-tenant.yaml \
	--wait -v

m '[openstack] Creating hello-world'
"$ROOT/openstack/openstack-tenant" hello-world hello-world hello-world-admin password \
stack create hello-world \
	--template /home/manager/workloads/hello-world.yaml \
	--wait -v

m '[openstack] Fetching hello-world private key'

"$ROOT/openstack/openstack-tenant" hello-world hello-world hello-world-admin password \
stack output show hello-world private-key --format value --column output_value \
	> "$KEYS_ROOT/centos@hello-world"

chmod 600 "$KEYS_ROOT/centos@hello-world"

"$ROOT/rsync" \
	"$KEYS_ROOT/centos@hello-world" \
	lab-controller-0:

IP_ADDRESS=$("$ROOT/openstack/openstack-tenant" hello-world hello-world hello-world-admin password \
stack output show hello-world public-ip --format value --column output_value)

m "[openstack] Server's public IP address: $IP_ADDRESS"

"$ROOT/utils/ensure-ssh-config-proxy" hello-world "$IP_ADDRESS" centos centos@hello-world lab-controller-0
