#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-fetch-results"

"$ROOT/ssh" tripleo "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	. "\$HOME/stackrc"

	m '[tripleo] Ensuring no infrastructure nodes'

	for UUID in \$(openstack baremetal node list --format value --column UUID); do
		m "[tripleo] Deleting infrastructure node \"\$UUID\""
		openstack baremetal node maintenance set "\$UUID" $(c "$TRIPLEO_VERBOSITY") || true
		openstack baremetal node delete "\$UUID" $(c "$TRIPLEO_VERBOSITY")
	done

EOT
)"

"$ROOT/ssh" manager-root "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	m '[manager-root] Ensuring no virtual machines for infrastructure nodes'

	function d () {
		m "[manager-root] Deleting virtual machine \"\$1\""
		virsh destroy "\$1" || true
		virsh undefine "\$1" || true
		rm --force "/home/manager/libvirt/images/\$1.qcow2"
	}

	d openstack-controller
	d openstack-compute

EOT
)"
