#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

m "[tripleo] Fetching infrastructure access keypair"

"$ROOT/rsync" \
	tripleo:/home/stack/.ssh/id_rsa \
	"$KEYS_ROOT/tripleo"

"$ROOT/rsync" \
	tripleo:/home/stack/.ssh/id_rsa.pub \
	"$KEYS_ROOT/tripleo.pub"

for NAME in $("$ROOT/manager/tripleo/openstack" server list --format value --column Name); do
	EQ_NAME=$(eq "$NAME")
	IP_ADDRESS=$("$HERE/get-ipv4-address" "$NAME" ctlplane)
	if [ -n "$IP_ADDRESS" ]; then
		m "[tripleo] Enabling ssh access to infrastructure server \"$EQ_NAME\" via ctlplane: $IP_ADDRESS"
		"$ROOT/utils/ensure-ssh-config-proxy" "$NAME" "$IP_ADDRESS" heat-admin tripleo tripleo
	else
		m "[tripleo] Infrastructure server \"$EQ_NAME\" does not have an IP address on ctlplane" "$RED"
	fi
done
