#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# Note: use "_" instead of "-" for NETWORK

NAME=$1
NETWORK=$2

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

EQ_NAME=$(eq "$NAME")

ADDRESSES=$("$ROOT/hypervisor/tripleo/openstack" server show "$NAME" --format value --column addresses | sed 's/\-/_/g')
eval "$ADDRESSES"
echo "${!NETWORK}"
