#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/basic_deployment/basic_deployment_cli.html#get-images

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$ROOT/hypervisor/rsync" \
	"$ROOT/configuration/tripleo/overcloud-deploy-answers.yaml" \
	tripleo-stack:

MAC_ADDRESSES=$("$ROOT/hypervisor/ssh" hypervisor-root "$(cat <<- EOT
	set -e
	virsh domiflist overcloud-controller |
		tail --lines=+3 |
		head --lines=-1 |
		awk '{ split(\$5,a,"/"); print \$3 "=" a[1] }' |
		sed 's/\-/_/g'
EOT
)")

eval "$MAC_ADDRESSES"
if [ -z "$os_ctlplane" ]; then
	exit 1
fi

OVERCLOUD_INFRASTRUCTURE_YAML=$(cat "$ROOT/configuration/tripleo/overcloud-infrastructure.yaml" |
	CONTROLLER_MAC_ADDRESS=$(eq "$os_ctlplane") \
	COMPUTE_MAC_ADDRESS=$(eq "$COMPUTE_MAC_ADDRESS") \
	envsubst)

"$ROOT/hypervisor/ssh" -t tripleo-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	. "\$HOME/stackrc"

	#openstack baremetal node maintenance set overcloud-controller
	#openstack baremetal node delete overcloud-controller

	m '[tripleo-stack] Updating overcloud infrastructure configuration'
	echo $(c "$OVERCLOUD_INFRASTRUCTURE_YAML") > "\$HOME/overcloud-infrastructure.yaml"
	openstack overcloud node import "\$HOME/overcloud-infrastructure.yaml"

	#openstack baremetal node list

	m '[tripleo-stack] Introspecting overcloud nodes (~ 15 minutes)'
	#openstack overcloud node introspect --all-manageable

	m '[tripleo-stack] Ensuring overcloud nodes are "available"'
	#openstack overcloud node provide --all-manageable

	m '[tripleo-stack] Deploying'
	#openstack overcloud deploy --templates --answers-file "\$HOME/overcloud-deploy-answers.yaml"

	#openstack stack resource list overcloud
	#openstack stack resource show overcloud ControllerServiceChain

EOT
)"

m "Finished $(q "$(basename "$0")")!"
