#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/basic_deployment/basic_deployment_cli.html#get-images

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-fetch-results"

if [ -n "$CONTROLLER_VIRTUALBMC_PORT" ]; then
	CONTROLLER_MAC_ADDRESS=$("$ROOT/hypervisor/get-mac-address" openstack-controller os_ctlplane)
fi

if [ -n "$COMPUTE_VIRTUALBMC_PORT" ]; then
	COMPUTE_MAC_ADDRESS=$("$ROOT/hypervisor/get-mac-address" openstack-compute os_ctlplane)
fi

INFRASTRUCTURE_NODES_YAML=$(cat "$ROOT/configuration/tripleo/infrastructure-nodes.yaml" |
	CONTROLLER_MAC_ADDRESS=$(eq "$CONTROLLER_MAC_ADDRESS") \
	CONTROLLER_VIRTUALBMC_PORT=$(eq "$CONTROLLER_VIRTUALBMC_PORT") \
	COMPUTE_MAC_ADDRESS=$(eq "$COMPUTE_MAC_ADDRESS") \
	COMPUTE_VIRTUALBMC_PORT=$(eq "$COMPUTE_VIRTUALBMC_PORT") \
	VIRTUALBMC_USERNAME=$(eq "$VIRTUALBMC_USERNAME") \
	VIRTUALBMC_PASSWORD=$(eq "$VIRTUALBMC_PASSWORD") \
	envsubst)

"$ROOT/hypervisor/ssh" -t tripleo-stack "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	. "\$HOME/stackrc"

	# Note: Existing baremetal nodes will be updated, but nodes missing from the file  will *not*
	# be deleted. To manually delete, e.g.:
	#
	#   openstack baremetal node maintenance set controller
	#   openstack baremetal node delete controller

	m '[tripleo-stack] Updating infrastructure node definitions'
	echo $(c "$INFRASTRUCTURE_NODES_YAML") > "\$HOME/infrastructure-nodes.yaml"
	openstack overcloud node import "\$HOME/infrastructure-nodes.yaml"

	m '[tripleo-stack] Introspecting infrastructure nodes (~ 15 minutes)'
	openstack overcloud node introspect \
		--all-manageable \
		-vvv

	mkdir --parents "\$HOME/introspection"
	for NAME in \$(openstack baremetal node list --format value --column Name); do
		m "[tripleo-stack] Retrieving introspection results infrastructure node \"\$NAME\""
		openstack baremetal introspection data save "\$NAME" | \
			jq -M . > "\$HOME/introspection/\$NAME.json"
	done

	m '[tripleo-stack] Ensuring infrastructure nodes are "available"'
	openstack overcloud node provide \
		--all-manageable

EOT
)"
