#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

EQ_TRIPLEO_VERSION=$(eq "$TRIPLEO_VERSION")
EQ_CEPH_VERSION=$(eq "$CEPH_VERSION")

# Using "-t" to improve wget display
"$ROOT/ssh" -t tripleo "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	if [ ! -f "\$HOME/images/centos7.qcow2" ]; then
		m "[tripleo] Downloading base image: \"\$HOME/images/centos7.qcow2\""
		mkdir --parents "\$HOME/images/"
		wget --output-document="\$HOME/images/centos7.qcow2" $(c "$CENTOS7_IMAGE")
	fi

	. "\$HOME/stackrc"

	m '[tripleo] Ensuring infrastructure images are built (~ 5 minutes)'
	DIB_YUM_REPO_CONF="/etc/yum.repos.d/delorean.repo /etc/yum.repos.d/delorean-$EQ_TRIPLEO_VERSION-testing.repo /etc/yum.repos.d/tripleo-centos-ceph-$EQ_CEPH_VERSION.repo" \
	DIB_LOCAL_IMAGE="\$HOME/images/centos7.qcow2" \
	openstack \
	overcloud image build \
		$(c "$TRIPLEO_VERBOSITY")

	m '[tripleo] Ensuring infrastructure images are uploaded'
	openstack \
	overcloud image upload \
		$(c "$TRIPLEO_VERBOSITY")

EOT
)"

if [ -n "$CONTROLLER_VIRTUALBMC_PORT" ]; then
	"$ROOT/manager/create-virtual-machine" openstack-controller
	"$ROOT/manager/enable-virtual-machine-virtualbmc" openstack-controller "$CONTROLLER_VIRTUALBMC_PORT"
fi

if [ -n "$COMPUTE_VIRTUALBMC_PORT" ]; then
	"$ROOT/manager/create-virtual-machine" openstack-compute
	"$ROOT/manager/enable-virtual-machine-virtualbmc" openstack-compute "$COMPUTE_VIRTUALBMC_PORT"
fi
