#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1

if [ -z "$PROJECT" ]; then
	echo 'Provide project name'
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"

"$HERE/create-image" "$PROJECT" centos7 /home/stack/images/centos7.qcow2
