#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1
NAME=$2
IMAGE=$3

if [ -z "$PROJECT" ] || [ -z "$NAME" ] || [ -z "$IMAGE" ]; then
	echo 'Provide project name, image name, and image path'
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

if ! "$ROOT/openstack/openstack" image show "$PROJECT.$NAME" > /dev/null 2>&1; then

	m "Creating image \"$PROJECT.$NAME\"..."
	"$ROOT/openstack/openstack" image create "$PROJECT.$NAME" \
		--project "$PROJECT" \
		--file "$IMAGE" \
		--disk-format qcow2 \
		--container-format bare \
		--public

else

	m "Image \"$PROJECT.$NAME\" already exists"
	exit 1

fi
