#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

# NOTE: public flavors cannot be associated with projects

"$HERE/openstack" flavor create --id 0 --ram 512  --vcpus 1 --disk 10  m1.tiny
"$HERE/openstack" flavor create --id 1 --ram 1024 --vcpus 1 --disk 20  m1.small
"$HERE/openstack" flavor create --id 2 --ram 2048 --vcpus 2 --disk 40  m1.medium
"$HERE/openstack" flavor create --id 3 --ram 4096 --vcpus 2 --disk 80  m1.large
"$HERE/openstack" flavor create --id 4 --ram 8192 --vcpus 4 --disk 160 m1.xlarge
