#!/bin/bash
set -e

PASSWORD_PATH=$1

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/functions"

if [ ! -f "$PASSWORD_PATH" ]; then
	echo "$(random_password)" > "$PASSWORD_PATH"
fi

cat "$PASSWORD_PATH"
