#!/bin/bash
set -e

NAME=$1
HOST=$2
USERNAME=$3
KEY=$4
PROXY=$5

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$HERE/delete-ssh-config" "$NAME"

# Since OpenSSH 7.3 ("-J"):
#   ProxyJump "$PROXY"
# Which is equivalent to:
#   ProxyCommand ssh -F "$CONFIG" "$PROXY" -W %h:%p
# Oldest way (requires "nc" on proxy):
#   ProxyCommand ssh -F "$CONFIG" "$PROXY" "nc %h %p"

cat >> "$WORKSPACE_ROOT/ssh.config" <<- EOT
	Host "$NAME"
	  HostName "$HOST"
	  User "$USERNAME"
	  IdentityFile "$KEYS_ROOT/$KEY"
	  StrictHostKeyChecking no
	  UserKnownHostsFile /dev/null
	  LogLevel ERROR
	  ProxyJump "$PROXY"

EOT
