#!/bin/bash
set -e

# ssh-copy-id is unfortunately buggy and will create duplicate keys
# See: https://superuser.com/a/264401

KEY_PATH=$1

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/functions"

Q_KEY="$(q "$(cat "$KEY_PATH")")"

"${@:2}" \
"echo $Q_KEY | while read -r KTYPE KEY COMMENT; do
	if ! (grep --no-messages --fixed-strings --word-regexp \"\$KTYPE \$KEY\" ~/.ssh/authorized_keys | grep --quiet --invert-match --fixed-strings '^#'); then
		mkdir --parents --mode=0700 ~/.ssh
		echo \"\$KTYPE \$KEY \$COMMENT\" >> ~/.ssh/authorized_keys
		chmod 600 ~/.ssh/authorized_keys
	else
		echo 'Already authorized'
	fi
done"
