#!/bin/bash
set -e

PASSWORD=$1

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

if [ ! -f "$PASSWORDS_ROOT/$PASSWORD" ]; then
	mkdir --parents "$PASSWORDS_ROOT"
	echo "$(random_password)" > "$PASSWORDS_ROOT/$PASSWORD"
fi

cat "$PASSWORDS_ROOT/$PASSWORD"
