#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/basic_deployment/basic_deployment_cli.html#get-images

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$ROOT/hypervisor/rsync" \
	"$ROOT/configuration/tripleo/instackenv.yaml" \
	"$ROOT/configuration/tripleo/overcloud-deploy-answers.yaml" \
	undercloud-stack:

"$ROOT/hypervisor/ssh" -t undercloud-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	m '[undercloud] Ensuring instackenv is uploaded'
	openstack overcloud node import "\$HOME/instackenv.yaml"

	#openstack baremetal node list

	m '[undercloud] Introspecting (~ 15 minutes)'
	#openstack overcloud node introspect --all-manageable

	m '[undercloud] Ensuring overcloud nodes are "available"'
	#openstack overcloud node provide --all-manageable

	m '[undercloud] Deploying'
	#openstack overcloud deploy --templates --answers-file "\$HOME/overcloud-deploy-answers.yaml"

	#openstack stack resource list overcloud
	#openstack stack resource show overcloud ControllerServiceChain

EOT
)"

m "Finished $(q "$(basename "$0")")!"
