#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

# See: https://docs.openstack.org/tripleo-docs/latest/install/installation/installation.html

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$ROOT/hypervisor/create-virtual-machine" overcloud-controller 80G centos7 "$CENTOS7_IMAGE"

"$ROOT/hypervisor/ssh" hypervisor-stack "$(cat <<- EOT

	vbmc add overcloud-controller \
		--libvirt-uri "qemu:///session?socket=\$XDG_RUNTIME_DIR/libvirt/libvirt-sock" \
		--address 127.0.0.1 \
		--port 6230

	vbmc start overcloud-controller

	#ipmitool -I lanplus -U admin -P password -H 127.0.0.1 -p 6230 power off

EOT
)"

"$ROOT/hypervisor/ssh" -t undercloud-stack "$(cat <<- EOT

	set -e
	GREEN='\033[0;32m'
	RESET='\033[0m'
	function m () { echo -e "\$GREEN\$1\$RESET"; }

	if [ ! -f "\$HOME/images/centos7.qcow2" ]; then
		m "[hypervisor] Downloading base image: \"\$HOME/images/centos7.qcow2\""
		mkdir --parents "\$HOME/images/"
		wget --output-document="\$HOME/images/centos7.qcow2" $(c "$CENTOS7_IMAGE")
	fi

	. "\$HOME/stackrc"

	m '[undercloud] Ensuring overcloud images are built (~ 5 minutes)'
	export DIB_YUM_REPO_CONF="/etc/yum.repos.d/delorean.repo /etc/yum.repos.d/delorean-stein-testing.repo /etc/yum.repos.d/tripleo-centos-ceph-luminous.repo"
	export DIB_LOCAL_IMAGE="\$HOME/images/centos7.qcow2"
	openstack overcloud image build

	m '[undercloud] Ensuring overcloud images are uploaded'
	openstack overcloud image upload

EOT
)"

m "Finished $(q "$(basename "$0")")!"
