#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
	"$HERE/infrastructure/clean"
fi

"$HERE/infrastructure/all"
"$HERE/deploy"
"$HERE/connect"
"$HERE/common/deploy"
