#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

"$ROOT/manager/tripleo/openstack" \
overcloud delete "$TRIPLEO_OVERCLOUD_HEAT_STACK" \
	--yes

"$ROOT/manager/tripleo/openstack" \
baremetal node manage computehci

"$ROOT/manager/tripleo/openstack" \
overcloud node clean computehci

"$ROOT/manager/tripleo/openstack" \
overcloud node provide computehci

"$ROOT/utils/delete-ssh-config" openstack-dashboard
