#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

"$ROOT/rsync" \
	tripleo:/home/tripleo/labrc \
	"$WORKSPACE_ROOT/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc"

"$ROOT/rsync" \
	"$WORKSPACE_ROOT/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc" \
	"manager:/home/manager/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc"

CONTROLLER_IP_ADDRESS=$("$ROOT/manager/get-ipv4-address" openstack-controller br-public)

if [ -z "$CONTROLLER_IP_ADDRESS" ]; then
	m '[manager] Controller does not have an IP address on public network' "$RED"
	exit 1
fi

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$REMOTE_PREAMBLE

	m '[manager] Enabling IP route to External network via controller on public network'

	# TODO make permanent
	ip route del 10.0.0.0/24 || true
	ip route add 10.0.0.0/24 via $(c "$CONTROLLER_IP_ADDRESS") || true

EOT
)"

. "$WORKSPACE_ROOT/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc"

# TODO extract IP and password

echo "$OS_AUTH_URL"

m "[manager] Enabling dashboard port $OPENSTACK_LOCAL_DASHBOARD_PORT forwarded via ssh \"openstack-dashboard\""

"$ROOT/utils/ensure-ssh-config-forward" openstack-dashboard "$MANAGER_IP_ADDRESS" manager manager@manager "$OPENSTACK_LOCAL_DASHBOARD_PORT" 10.0.0.70:80
