#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1
NAME=$2
URL=$3

if [ -z "$PROJECT" ] || [ -z "$NAME" ] || [ -z "$URL" ]; then
	echo 'Provide project name, image name, and image URL'
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/conf/env"

if ! "$HERE/openstack" image show "$PROJECT.$NAME" >/dev/null 2>&1; then
	FILENAME="$OPENSTACK_IMAGES/$(basename "$URL")"

	"$ROOT/hypervisor/ssh" undercloud "
mkdir --parents \"$OPENSTACK_IMAGES\";
if [ ! -f \"$FILENAME\" ]; then
	curl --output \"$FILENAME\" \"$URL\";
fi
"

	echo "Creating image \"$PROJECT.$NAME\"..."
	"$HERE/openstack" image create "$PROJECT.$NAME" \
		--project "$PROJECT" \
		--file "$FILENAME" \
		--disk-format qcow2 \
		--container-format bare \
		--public
else
	echo "Image \"$PROJECT.$NAME\" already exists"
	exit 1
fi
