#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == 'stop' ]; then

	# See: https://stackoverflow.com/a/15198031
	"$ROOT/ssh" \
		-o ControlMaster=no \
		-S "$SSH_CONTROL_ROOT/openstack-dashboard" \
		-O exit \
		openstack-dashboard

else

	"$ROOT/ssh" -fN openstack-dashboard

	xdg-open "http://localhost:$OPENSTACK_LOCAL_DASHBOARD_PORT"

fi
