#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$HERE/openstack" network create public \
	--external \
	--default \
	--share \
	--provider-network-type flat \
	--provider-physical-network datacentre || true

"$HERE/openstack" subnet create public \
	--network public \
	--subnet-range 192.168.25.0/24 \
	--allocation-pool start=192.168.25.2,end=192.168.25.254 \
	--gateway 192.168.122.1 \
	--dns-nameserver 1.0.0.1 \
	--no-dhcp || true

router create public
router set $ROUTER_ID --external-gateway public
