#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")

"$HERE/create-common-flavors"
"$HERE/openstack" project create common
"$HERE/create-common-images" common
