#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-fetch-results"

OVERCLOUD_DEPLOY_ANSWERS_YAML=$(cat "$ROOT/configuration/tripleo/overcloud-deploy-answers.yaml" |
	HOME=/home/stack \
	envsubst)

"$ROOT/hypervisor/ssh" -t tripleo-stack "$(cat <<- EOT

	set -e
	CYAN='\033[0;36m'
	RESET='\033[0m'
	function m () { echo -e "\$CYAN\$1\$RESET"; }

	. "\$HOME/stackrc"

	m '[tripleo-stack] Deploying overcloud'
	echo $(c "$OVERCLOUD_DEPLOY_ANSWERS_YAML") > "\$HOME/overcloud-deploy-answers.yaml"
	openstack overcloud deploy \
		--templates \
		--answers-file "\$HOME/overcloud-deploy-answers.yaml" \
		-vvv

	#openstack stack resource list overcloud
	#openstack stack resource show overcloud ControllerServiceChain

EOT
)"
