#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT_NAME=$1
Q_PROJECT_NAME=$(q "$PROJECT_NAME")

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/utils/functions"

# For quality of life we will make sure that the "openstack" command (Cliff) will limit
# its output width to the width of our terminal

"$ROOT/ssh" tripleo \
". \$HOME/overcloudrc && CLIFF_MAX_TERM_WIDTH=$(tput cols) OS_PROJECT_NAME=$Q_PROJECT_NAME openstack $(c "${@:2}")"
