#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")

"$ROOT/hypervisor/ssh" undercloud ". /home/stack/overcloudrc && openstack $(printf ' %q' "$@")"
