#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

# For quality of life we will make sure that the "openstack" command (Cliff) will always limit its
# output width to the width of our terminal ("CLIFF_FIT_WIDTH=1" doesn't seem to work)

"$ROOT/ssh" manager \
". \"\$HOME/${OVERCLOUD_HEAT_STACK}rc\" 
CLIFF_MAX_TERM_WIDTH=\"$(tput cols)\" \
\"\$HOME/.local/bin/openstack\" $(c "$@")"
