#!/bin/bash
set -e

if [ "$EUID" == 0 ]; then
	echo "Do not run this script as root"
	exit 1
fi

PROJECT=$1
USERNAME=$2
PASSWORD=$3

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/utils/functions"

# For quality of life we will make sure that the "openstack" command (Cliff) will always limit its
# output width to the width of our terminal ("CLIFF_FIT_WIDTH=1" doesn't seem to work)

"$ROOT/ssh" manager \
". \"\$HOME/labrc\" 
CLIFF_MAX_TERM_WIDTH=\"$(tput cols)\" \
OS_PROJECT_NAME=$(c "$PROJECT") \
OS_USERNAME=$(c "$USERNAME") \
OS_PASSWORD=$(c "$PASSWORD") \
\"\$HOME/.local/bin/openstack\" $(c "${@:4}")"
