# See: https://docs.openstack.org/heat/stein/template_guide/

heat_template_version: 2018-08-31

description: >-
  Hello World

resources:

  # Networking

  net:
    type: OS::Neutron::Net
    properties:
      name: hello-world

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net }
      ip_version: 4
      cidr: 192.0.2.0/24
      dns_nameservers:
      - 1.0.0.1

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: public

  router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  security-group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: control-plane
      rules:
      - remote_ip_prefix: 0.0.0.0/0
        direction: ingress
        protocol: icmp
      - remote_ip_prefix: 0.0.0.0/0
        direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22

  port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net }
      fixed_ips:
      - subnet_id: { get_resource: subnet }
      security_groups:
      - { get_resource: security-group }

  floating-ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public
      port_id: { get_resource: port } 

  # Server

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: hello-world
      save_private_key: true

  server:
    type: OS::Nova::Server
    properties:
      name: server
      flavor: m1.tiny
      image: centos7
      key_name: { get_resource: keypair }
      networks:
      - port: { get_resource: port }

  # Volume

  volume:
    type: OS::Cinder::Volume
    properties:
      size: 5 # GB

  volume-attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: server }
      #mountpoint: /dev/vdb

outputs:

  # openstack/openstack-project hello-world hello-world-admin admin stack output show hello-world private-key --format value --column output_value
  # user: centos

  private-key:
    description: Private key
    value: { get_attr: [ keypair, private_key ] }

  private-ip:
    description: Private IP address
    value: { get_attr: [ server, first_address ] }

  public-ip:
    description: Public IP address
    value: { get_attr: [ floating-ip, floating_ip_address ] }
